apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: ghcr.io/charles1303/kube-argocd-deploy:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
